"""Build Persona v2 draft dictionaries from parsed source."""

from __future__ import annotations

from typing import Any

from .models import ImportIssue, ImportReport, ImportResult, ReportField, SourceDocument, SourceField, SourceSpan
from .parser import bullet_items, first_prefixed_value, list_after_label

DRAFT_YAML_FILES = (
    "persona.yaml",
    "voice.yaml",
    "runtime.yaml",
    "knowledge.yaml",
    "relationships.yaml",
    "memory.yaml",
    "capabilities.yaml",
    "adapter.yaml",
    "guard.yaml",
    "examples.yaml",
    "eval.yaml",
    "trace.yaml",
    "state.yaml",
    "thinker.yaml",
    "system.yaml",
)

DEFAULT_TEMPLATE_FILES = ("guard.yaml", "eval.yaml", "trace.yaml")


def build_persona_draft(
    source: SourceDocument,
    *,
    defaults: dict[str, dict[str, Any]] | None = None,
) -> ImportResult:
    persona_id = _frontmatter_str(source, "persona_id") or "unknown-v2"
    report = ImportReport(
        persona_id=persona_id,
        source_file=source.path,
        source_hash=source.source_hash,
    )

    draft = _empty_draft(persona_id, source)
    defaults = defaults or {}
    for filename, payload in defaults.items():
        if filename in DEFAULT_TEMPLATE_FILES and isinstance(payload, dict):
            draft[filename] = payload
            report.fields.append(
                ReportField(
                    file=filename,
                    key_path=".",
                    source_span=None,
                    confidence=1.0,
                    extractor="default_template",
                    default_used=True,
                    issue_level="info",
                )
            )

    _extract_frontmatter(source, draft, report)
    _extract_identity(source, draft, report)
    _extract_voice(source, draft, report)
    _extract_knowledge(source, draft, report)
    _extract_examples(source, draft, report)
    _validate_required(draft, report)

    report.generated_files = [
        *DRAFT_YAML_FILES,
        "modules/_README.md",
        "_import_report.json",
    ]
    return ImportResult(
        persona_id=persona_id,
        draft=draft,
        modules_readme=_modules_readme(persona_id),
        report=report,
    )


def _empty_draft(persona_id: str, source: SourceDocument) -> dict[str, dict[str, Any]]:
    return {
        "persona.yaml": {
            "schema": "omubot.persona.v2",
            "version": "2.1.0-proposal",
            "id": persona_id,
            "identity": {
                "canonical_name": "",
                "aliases": [],
                "role": "",
                "self_reference": "",
                "essence": [],
                "not_traits": [],
            },
            "constitution": {
                "values": [],
                "hard_rules": [],
            },
            "runtime_state_seed": {},
        },
        "voice.yaml": {
            "schema": "omubot.voice.v2",
            "version": "2.1.0-proposal",
            "language": "",
            "style_principles": {
                "sentence_shape": [],
                "rhythm": [],
                "banned_patterns": [],
            },
            "expression_library": {"items": []},
            "slang_policy": {},
        },
        "runtime.yaml": _skeleton("omubot.runtime.v2", source),
        "knowledge.yaml": {
            "schema": "omubot.knowledge.v2",
            "version": "2.1.0-proposal",
            "known_facts": [],
            "unknown_boundaries": [],
            "forbidden_claims": [],
        },
        "relationships.yaml": {
            "schema": "omubot.relationships.v2",
            "version": "2.1.0-proposal",
            "default_disposition": "",
            "profiles": [],
        },
        "memory.yaml": {
            "schema": "omubot.memory.v2",
            "version": "2.1.0-proposal",
            "seed_episodes": [],
        },
        "capabilities.yaml": _skeleton("omubot.capabilities.v2", source),
        "adapter.yaml": _skeleton("omubot.adapter.v2", source),
        "guard.yaml": _skeleton("omubot.guard.v2", source),
        "examples.yaml": {
            "schema": "omubot.examples.v2",
            "version": "2.1.0-proposal",
            "positive": [],
            "negative": [],
        },
        "eval.yaml": _skeleton("omubot.persona_eval.v2", source),
        "trace.yaml": _skeleton("omubot.trace.v2", source),
        "state.yaml": _skeleton("omubot.state.v2", source),
        "thinker.yaml": _skeleton("omubot.thinker.v2", source),
        "system.yaml": _skeleton("omubot.system.v2", source),
    }


def _skeleton(schema: str, source: SourceDocument) -> dict[str, Any]:
    return {
        "schema": schema,
        "version": "2.1.0-proposal",
        "status": "skeleton",
        "todo": "Generated by Persona Source Importer Part A; fill in later stages.",
        "source_hash": source.source_hash,
    }


def _extract_frontmatter(source: SourceDocument, draft: dict[str, dict[str, Any]], report: ImportReport) -> None:
    for key, target in (
        ("persona_id", ("persona.yaml", "id")),
        ("canonical_name", ("persona.yaml", "identity.canonical_name")),
        ("language", ("voice.yaml", "language")),
    ):
        value = _frontmatter_str(source, key)
        if not value:
            report.issues.append(
                ImportIssue("error", "missing_frontmatter", f"front matter `{key}` 缺失", target[0], target[1])
            )
            continue
        _set_path(draft[target[0]], target[1], value)
        report.fields.append(
            ReportField(
                file=target[0],
                key_path=target[1],
                source_span=SourceSpan(source.path, (1, max(1, _frontmatter_end_line(source.text)))),
                confidence=1.0,
                extractor="front_matter",
            )
        )


def _extract_identity(source: SourceDocument, draft: dict[str, dict[str, Any]], report: ImportReport) -> None:
    root = source.section("是谁")
    essence = source.section("性格底色")
    not_traits = source.section("不应该", "不应出现")
    rules = source.section("价值观", "硬规则")

    role = first_prefixed_value(root, "一句话角色", source_file=source.path)
    self_ref = first_prefixed_value(root, "自称", source_file=source.path)
    _set_field(draft, report, "persona.yaml", "identity.role", role, "sentence_md")
    _set_field(draft, report, "persona.yaml", "identity.self_reference", self_ref, "sentence_md")
    _set_list(
        draft,
        report,
        "persona.yaml",
        "identity.essence",
        bullet_items(essence, source_file=source.path),
        "list_md",
    )
    _set_list(
        draft,
        report,
        "persona.yaml",
        "identity.not_traits",
        bullet_items(not_traits, source_file=source.path),
        "list_md",
    )
    _set_list(
        draft,
        report,
        "persona.yaml",
        "constitution.values",
        list_after_label(rules, "价值观", source_file=source.path),
        "list_md",
    )

    hard_rules = []
    for item in list_after_label(rules, "硬规则", source_file=source.path):
        text, enforce = _split_enforce(str(item.value))
        hard_rules.append(
            SourceField(
                key=item.key,
                value={"text": text, "enforce": enforce},
                span=item.span,
            )
        )
    _set_list(draft, report, "persona.yaml", "constitution.hard_rules", hard_rules, "list_md")


def _extract_voice(source: SourceDocument, draft: dict[str, dict[str, Any]], report: ImportReport) -> None:
    voice = source.section("怎么说话")
    items = bullet_items(voice, source_file=source.path)
    _set_list(draft, report, "voice.yaml", "style_principles.sentence_shape", items, "list_md")
    _set_list(draft, report, "voice.yaml", "style_principles.rhythm", [], "list_md")
    banned = [item for item in items if "不" in str(item.value) or "禁" in str(item.value)]
    _set_list(draft, report, "voice.yaml", "style_principles.banned_patterns", banned, "list_md")
    expression_items = [
        SourceField(
            key=item.key,
            value={
                "text": item.value,
                "use_when": "",
                "avoid_when": "",
                "review_status": "candidate",
            },
            span=item.span,
        )
        for item in items
    ]
    _set_list(draft, report, "voice.yaml", "expression_library.items", expression_items, "list_md")


def _extract_knowledge(source: SourceDocument, draft: dict[str, dict[str, Any]], report: ImportReport) -> None:
    knowledge = source.section("知道什么", "不知道")
    mappings = (
        ("已知事实", "knowledge.yaml", "known_facts"),
        ("不知道边界", "knowledge.yaml", "unknown_boundaries"),
        ("禁说事实", "knowledge.yaml", "forbidden_claims"),
    )
    for label, filename, key_path in mappings:
        field = first_prefixed_value(knowledge, label, source_file=source.path)
        values: list[SourceField] = []
        if field is not None:
            values.append(field)
        values.extend(list_after_label(knowledge, label, source_file=source.path))
        _set_list(draft, report, filename, key_path, values, "list_md")


def _extract_examples(source: SourceDocument, draft: dict[str, dict[str, Any]], report: ImportReport) -> None:
    examples = source.section("例子")
    positives = [
        SourceField("positive", {"turn": item.value, "scene": "", "comment": ""}, item.span)
        for item in list_after_label(examples, "正例", source_file=source.path)
    ]
    negatives = [
        SourceField("negative", {"wrong_turn": item.value, "right_turn": ""}, item.span)
        for item in list_after_label(examples, "反例", source_file=source.path)
    ]
    _set_list(draft, report, "examples.yaml", "positive", positives, "llm_extract_stub")
    _set_list(draft, report, "examples.yaml", "negative", negatives, "llm_extract_stub")


def _validate_required(draft: dict[str, dict[str, Any]], report: ImportReport) -> None:
    required = (
        ("persona.yaml", "id", "persona_id"),
        ("persona.yaml", "identity.canonical_name", "canonical_name"),
        ("persona.yaml", "identity.role", "一句话角色"),
        ("persona.yaml", "identity.self_reference", "自称"),
        ("persona.yaml", "identity.essence", "性格底色"),
        ("persona.yaml", "identity.not_traits", "不应该出现的样子"),
        ("persona.yaml", "constitution.values", "价值观"),
        ("persona.yaml", "constitution.hard_rules", "硬规则"),
        ("voice.yaml", "language", "language"),
        ("voice.yaml", "style_principles.sentence_shape", "怎么说话"),
        ("voice.yaml", "style_principles.banned_patterns", "禁用句式"),
        ("voice.yaml", "expression_library.items", "表达素材"),
        ("knowledge.yaml", "known_facts", "已知事实"),
        ("knowledge.yaml", "unknown_boundaries", "不知道边界"),
        ("knowledge.yaml", "forbidden_claims", "禁说事实"),
        ("examples.yaml", "positive", "正例"),
        ("examples.yaml", "negative", "反例"),
    )
    for filename, key_path, label in required:
        if _get_path(draft[filename], key_path):
            continue
        report.issues.append(
            ImportIssue(
                "error",
                "missing_required_field",
                f"`{label}` 缺失或无法抽取",
                filename,
                key_path,
            )
        )

    for index, rule in enumerate(_get_path(draft["persona.yaml"], "constitution.hard_rules") or []):
        if not isinstance(rule, dict) or rule.get("enforce") not in {
            "pattern_guardable",
            "judge_guardable",
            "eval_only",
        }:
            report.issues.append(
                ImportIssue(
                    "error",
                    "hard_rule_missing_enforce",
                    "每条 hard_rule 必须标注 enforce: pattern_guardable / judge_guardable / eval_only",
                    "persona.yaml",
                    f"constitution.hard_rules[{index}]",
                )
            )


def _set_field(
    draft: dict[str, dict[str, Any]],
    report: ImportReport,
    filename: str,
    key_path: str,
    field: SourceField | None,
    extractor: str,
) -> None:
    if field is None:
        return
    _set_path(draft[filename], key_path, field.value)
    report.fields.append(
        ReportField(filename, key_path, field.span, 1.0, extractor)
    )


def _set_list(
    draft: dict[str, dict[str, Any]],
    report: ImportReport,
    filename: str,
    key_path: str,
    fields: list[SourceField],
    extractor: str,
) -> None:
    values = [field.value for field in fields]
    _set_path(draft[filename], key_path, values)
    for index, field in enumerate(fields):
        report.fields.append(
            ReportField(filename, f"{key_path}[{index}]", field.span, 1.0, extractor)
        )


def _set_path(payload: dict[str, Any], key_path: str, value: Any) -> None:
    parts = key_path.split(".")
    cursor = payload
    for part in parts[:-1]:
        next_value = cursor.get(part)
        if not isinstance(next_value, dict):
            next_value = {}
            cursor[part] = next_value
        cursor = next_value
    cursor[parts[-1]] = value


def _get_path(payload: dict[str, Any], key_path: str) -> Any:
    cursor: Any = payload
    for part in key_path.split("."):
        if not isinstance(cursor, dict):
            return None
        cursor = cursor.get(part)
    return cursor


def _frontmatter_str(source: SourceDocument, key: str) -> str:
    value = source.frontmatter.get(key)
    return str(value).strip() if value is not None else ""


def _frontmatter_end_line(text: str) -> int:
    if not text.startswith("---"):
        return 1
    lines = text.split("\n")
    for index, line in enumerate(lines[1:], start=2):
        if line.strip() == "---":
            return index
    return 1


def _split_enforce(text: str) -> tuple[str, str]:
    marker = "# enforce:"
    if marker not in text:
        return text.strip(), ""
    body, enforce = text.split(marker, 1)
    return body.strip(), enforce.strip().split()[0] if enforce.strip() else ""


def _modules_readme(persona_id: str) -> str:
    return (
        f"# modules placeholder for {persona_id}\n\n"
        "Persona Source Importer Part A only creates this placeholder.\n"
        "Concrete `modules/<id>/module.yaml` files belong to Part B "
        "Runtime/SystemModule implementation.\n"
    )
